# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Selenium Java and Postman Test

on:
  workflow_dispatch

jobs:
  api-test:
    environment: staging
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: "18"
      - name: "Install newman"
        run: "npm install -g newman"
      - name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      - name: "Run tests"
        run: |
        cd api_test
        newman run Moduit.postman_collection.json -e reqres.in.postman_environment.json
        -r htmlextra"

  # build_and_ui-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'
  #       cache: maven
  #       server-id: github 
  #       settings-path: ${{ github.workspace }} 
  #   - name: Install Google Chrome 
  #     run: |
  #           chmod +x ./scripts/InstallChrome.sh
  #           ./scripts/InstallChrome.sh

  #   - name: Build with Maven
  #     run: |
  #           cd ui_test
  #           mvn -B package --file pom.xml